### PR TITLE
add support for forceShutdown

### PR DESCRIPTION
**Pull request by lee-elenbaas**

### CODE REVIEW

**Comment by lee-elenbaas** [comment]
if you will look at the coverage details:
the only lines not covered are: the https prototype extending (as before)
and in test.js (https://coveralls.io/builds/7879048/source?filename=test.js) only the lines that should be there to fail the test if the code reach them
i don't see how to up the coverage any more - i am open to suggestions

i just realized i am talking to a bot :)

**Comment by thedillonb** [comment]
Thanks!

**Comment by lee-elenbaas** [comment]
Any chance you can release this on npm?

**Comment by thedillonb** [comment]
@lee-elenbaas, yeah, the CI should have built it. Let me see what's going on. I'll release it ASAP.

**Comment by lee-elenbaas** [comment]
you probably just need to update the package version

**Comment by thedillonb** [comment]
@lee-elenbaas It's all set. Released as 1.1.0 since we added to the API.

**Comment by lee-elenbaas** [comment]
thanks - i am using it in https://github.com/luminati-io/luminati-proxy

**Pull request merged**
